### ISSUE TITLE
Remove ReadMe

### ISSUE THREAD

**Issue by derrisra** [derrisra/data-entry-crud-operation#7]
Could you please remove **Read Me**

[Refer this link](https://www.referthecontent.com)

![Capture](https://user-images.githubusercontent.com/62515391/107629675-7806dd80-6c88-11eb-85b3-4a5382cfe273.PNG)

**Comment by DerrisRasaiyah** [comment]
Can I do that for you?

**Comment by derrisra** [comment]
Please proceed

**Comment by DerrisRasaiyah** [comment]
Done that

**Comment by derrisra** [comment]
Great! TY!
